import Head from 'next/head'
import { Poppins } from 'next/font/google'
import Start from './components/start'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100','200','300','400','500','600','700','800','900']
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Standalone-React Next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/svg+xml" href="/react.png" />
      </Head>
      <main className={poppins.className}>
          <Start/>
      </main>
    </>
  )
}
